//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class BatRecord
{

  private string fileNameField;

  private string dateTimeField;

  private string samplerateField;

  private string gainField;

  private string inputFilterField;

  private string durationField;

  private string peakValueField;

  private BatRecordTrigger triggerField;

  private BatRecordGPS gPSField;

  public BatRecord()
  {
    gPSField = new BatRecordGPS();
    triggerField = new BatRecordTrigger();
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
  public string FileName
  {
    get
    {
      return this.fileNameField;
    }
    set
    {
      this.fileNameField = value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
  public string DateTime
  {
    get
    {
      return this.dateTimeField;
    }
    set
    {
      this.dateTimeField = value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
  public string Samplerate
  {
    get
    {
      return this.samplerateField;
    }
    set
    {
      this.samplerateField = value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
  public string Gain
  {
    get
    {
      return this.gainField;
    }
    set
    {
      this.gainField = value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
  public string InputFilter
  {
    get
    {
      return this.inputFilterField;
    }
    set
    {
      this.inputFilterField = value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
  public string Duration
  {
    get
    {
      return this.durationField;
    }
    set
    {
      this.durationField = value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
  public string PeakValue
  {
    get
    {
      return this.peakValueField;
    }
    set
    {
      this.peakValueField = value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
  public BatRecordTrigger Trigger
  {
    get
    {
      return this.triggerField;
    }
    set
    {
      this.triggerField = value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
  public BatRecordGPS GPS
  {
    get
    {
      return this.gPSField;
    }
    set
    {
      this.gPSField = value;
    }
  }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BatRecordTrigger
{

  private string levelField;

  private string filterField;

  private string frequencyField;

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
  public string Level
  {
    get
    {
      return this.levelField;
    }
    set
    {
      this.levelField = value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
  public string Filter
  {
    get
    {
      return this.filterField;
    }
    set
    {
      this.filterField = value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
  public string Frequency
  {
    get
    {
      return this.frequencyField;
    }
    set
    {
      this.frequencyField = value;
    }
  }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BatRecordGPS
{

  private string positionField;

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
  public string Position
  {
    get
    {
      return this.positionField;
    }
    set
    {
      this.positionField = value;
    }
  }
}

/*
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class NewDataSet
{

  private BatRecord[] itemsField;

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute("BatRecord")]
  public BatRecord[] Items
  {
    get
    {
      return this.itemsField;
    }
    set
    {
      this.itemsField = value;
    }
  }
}*/

