<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\libBioAcoustics\libBioAcoustics.vcxproj">
			<!-- Verhindert, dass .NET versucht, die native DLL als .NET-Assembly zu laden -->
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
			<!-- Definiert die Ausgabe des C++ Projekts als normalen Inhalt -->
			<OutputItemType>Content</OutputItemType>
			<!-- Kopiert die DLL bei jedem Build in das .NET Ausgabeverzeichnis -->
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<!-- Wichtig: Verhindert Fehler, da C++ keine TargetFrameworks kennt -->
			<SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>
		</ProjectReference>
	</ItemGroup>
	<ItemGroup>
		<!-- Relativer Pfad von der .csproj zur libfftw3-3.dll -->
		<None Include="..\libBioAcoustics\lib\libfftw3-3.dll">
			<!-- Sorgt für das Kopieren bei jedem Build, falls die Datei neuer ist -->
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<!-- GANZ WICHTIG: Link sorgt dafür, dass die Datei direkt im Root-Verzeichnis (neben der .exe) landet 
         und nicht die Quell-Ordnerstruktur (z.B. \ThirdParty\fftw\) im Ausgabeordner nachgebildet wird. -->
			<Link>libfftw3-3.dll</Link>
		</None>
	</ItemGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>kopf64.ico</ApplicationIcon>
    <StartupObject />
    <Win32Resource />
    <Authors>Christian Müller</Authors>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  
  <PropertyGroup> 
     <TargetFramework>net10.0-windows</TargetFramework> 
     <UseWPF>true</UseWPF> 
     <UseWindowsForms>true</UseWindowsForms> 
     <PlatformTarget>AnyCPU</PlatformTarget> 
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702; IDE1006; IDE0090; IDE1006; IDE0130; RG0000</NoWarn>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <NoWarn>1701;1702; IDE1006; IDE0090; IDE1006; IDE0130; RG0000</NoWarn>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702; IDE1006; IDE0090;IDE1006; IDE0130; RG0000</NoWarn>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <NoWarn>1701;1702; IDE1006; IDE0090;IDE1006; IDE0130; RG0000</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
    <None Remove="images\Actions_help_about_icon.png" />
    <None Remove="images\Bandpass.png" />
    <None Remove="images\Bat_icon-icons.com_Q.png" />
    <None Remove="images\Button-Blank-Blue.48.png" />
    <None Remove="images\Button-Blank-Red.48.png" />
    <None Remove="images\Button_Help_icon_32.png" />
    <None Remove="images\cancel_77947.png" />
    <None Remove="images\check.png" />
    <None Remove="images\color-palette.png" />
    <None Remove="images\danger-sign.png" />
    <None Remove="images\data-recovery.png" />
    <None Remove="images\data-transfer.png" />
    <None Remove="images\debug.png" />
    <None Remove="images\filter.png" />
    <None Remove="images\icons8-arrow-down.png" />
    <None Remove="images\icons8-arrow-left-64.png" />
    <None Remove="images\icons8-arrow-right-64.png" />
    <None Remove="images\icons8-arrow-up.png" />
    <None Remove="images\icons8-cleanup-noise-100.png" />
    <None Remove="images\icons8-edit-64.png" />
    <None Remove="images\icons8-enlarge-maximum.png" />
    <None Remove="images\icons8-folder-48.png" />
    <None Remove="images\icons8-minus-48.png" />
    <None Remove="images\icons8-offener-ordner-64.png" />
    <None Remove="images\icons8-plus-+-48.png" />
    <None Remove="images\icons8-save-48-exp.png" />
    <None Remove="images\icons8-save-48-import.png" />
    <None Remove="images\icons8-save-48.png" />
    <None Remove="images\icons8-save-as-48.png" />
    <None Remove="images\icons8-staubsauger-64.png" />
    <None Remove="images\icons8-zoom-in-64.png" />
    <None Remove="images\icons8-zoom-in-A-v-64.png" />
    <None Remove="images\icons8-zoom-in-cursor-64.png" />
    <None Remove="images\icons8-zoom-in-h-64.png" />
    <None Remove="images\icons8-zoom-in-v-64.png" />
    <None Remove="images\icons8-zoom-out-A-v-64.png" />
    <None Remove="images\icons8-zoom-out-h-64.png" />
    <None Remove="images\icons8-zoom-out-v-64.png" />
    <None Remove="images\magnifying-glass.png" />
    <None Remove="images\micCorr.png" />
    <None Remove="images\pause.png" />
    <None Remove="images\perfomance.png" />
    <None Remove="images\play-button-10x.png" />
    <None Remove="images\play-button-20x.png" />
    <None Remove="images\play-button.png" />
    <None Remove="images\play-HET.png" />
    <None Remove="images\query.png" />
    <None Remove="images\report.png" />
    <None Remove="images\scissors.png" />
    <None Remove="images\script.png" />
    <None Remove="images\settingscog_87317.png" />
    <None Remove="images\shoes.png" />
    <None Remove="images\simplescreenrecorder_94921.png" />
    <None Remove="images\splash.png" />
    <None Remove="images\stop.png" />
    <None Remove="images\tea-cup.png" />
    <None Remove="images\toolhammerconstruction_81806.png" />
    <None Remove="images\Undo_icon-icons.com_73701.png" />
    <None Remove="images\vcsupdaterequired_93493.png" />
    <None Remove="images\volume.png" />
    <None Remove="images\wav-file-format-symbol.png" />
    <None Remove="images\xml-dateiformatsymbol.png" />
  </ItemGroup>
  
  <ItemGroup>
    <Resource Include="images\Actions_help_about_icon.png" />
    <Resource Include="images\Bat_icon-icons.com_Q.png" />
    <Resource Include="images\Button-Blank-Blue.48.png" />
    <Resource Include="images\Button-Blank-Red.48.png" />
    <Resource Include="images\cancel_77947.png" />
    <Resource Include="images\check.png" />
    <Resource Include="images\danger-sign.png" />
    <Resource Include="images\debug.png" />
    <Resource Include="images\icons8-edit-64.png" />
    <Resource Include="images\icons8-folder-48.png" />
    <Resource Include="images\icons8-minus-48.png" />
    <Resource Include="images\icons8-plus-+-48.png" />
    <Resource Include="images\icons8-save-as-48.png" />
  </ItemGroup>
  
  
  <ItemGroup>
    <PackageReference Include="BunLabs.NAudio.Flac" Version="2.0.1" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.11" />
    <PackageReference Include="MySql.Data" Version="26.7.0" />
    <PackageReference Include="NAudio" Version="3.0.1" />
    <PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
    <PackageReference Include="System.IO.Ports" Version="10.0.11" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\libBioAcoustics\libBioAcoustics.vcxproj" />
    <ProjectReference Include="..\libScripter\libScripter.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="NAudio">
      <HintPath>..\packages\NAudio.2.2.1\lib\net6.0\NAudio.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <ItemGroup>
    <Resource Include="images\Bandpass.png" />
    <Resource Include="images\Button_Help_icon_32.png" />
    <Resource Include="images\color-palette.png" />
    <Resource Include="images\data-recovery.png" />
    <Resource Include="images\data-transfer.png" />
    <Resource Include="images\filter.png" />
    <Resource Include="images\icons8-arrow-down.png" />
    <Resource Include="images\icons8-arrow-left-64.png" />
    <Resource Include="images\icons8-arrow-right-64.png" />
    <Resource Include="images\icons8-arrow-up.png" />
    <Resource Include="images\icons8-cleanup-noise-100.png" />
    <Resource Include="images\icons8-enlarge-maximum.png" />
    <Resource Include="images\icons8-offener-ordner-64.png" />
    <Resource Include="images\icons8-save-48-exp.png" />
    <Resource Include="images\icons8-save-48-import.png" />
    <Resource Include="images\icons8-save-48.png" />
    <Resource Include="images\icons8-staubsauger-64.png" />
    <Resource Include="images\icons8-zoom-in-64.png" />
    <Resource Include="images\icons8-zoom-in-A-v-64.png" />
    <Resource Include="images\icons8-zoom-in-cursor-64.png" />
    <Resource Include="images\icons8-zoom-in-h-64.png" />
    <Resource Include="images\icons8-zoom-in-v-64.png" />
    <Resource Include="images\icons8-zoom-out-A-v-64.png" />
    <Resource Include="images\icons8-zoom-out-h-64.png" />
    <Resource Include="images\icons8-zoom-out-v-64.png" />
    <Resource Include="images\kopf64.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\magnifying-glass.png" />
    <Resource Include="images\micCorr.png" />
    <Resource Include="images\pause.png" />
    <Resource Include="images\perfomance.png" />
    <Resource Include="images\play-button-10x.png" />
    <Resource Include="images\play-button-20x.png" />
    <Resource Include="images\play-button.png" />
    <Resource Include="images\play-HET.png" />
    <Resource Include="images\query.png" />
    <Resource Include="images\report.png" />
    <Resource Include="images\scissors.png" />
    <Resource Include="images\script.png" />
    <Resource Include="images\settingscog_87317.png" />
    <Resource Include="images\shoes.png" />
    <Resource Include="images\simplescreenrecorder_94921.png" />
    <Resource Include="images\splash.png" />
    <Resource Include="images\stop.png" />
    <Resource Include="images\tea-cup.png" />
    <Resource Include="images\toolhammerconstruction_81806.png" />
    <Resource Include="images\Undo_icon-icons.com_73701.png" />
    <Resource Include="images\vcsupdaterequired_93493.png" />
    <Resource Include="images\volume.png" />
    <Resource Include="images\wav-file-format-symbol.png" />
    <Resource Include="images\xml-dateiformatsymbol.png" />
  </ItemGroup>

  
  <ItemGroup>
    <EmbeddedResource Update="Properties\MyResources.de.resx">
      <Generator></Generator>
      <CustomToolNamespace>F:\prj\BatInspector\BatInspector\Properties</CustomToolNamespace>
	</EmbeddedResource>
    <EmbeddedResource Update="Properties\MyResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MyResources.Designer.cs</LastGenOutput>
      <CustomToolNamespace>F:\prj\BatInspector\BatInspector\Properties</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\MyResources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>MyResources.resx</DependentUpon>
		</Compile>
		<Compile Update="Properties\Settings.Designer.cs">
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="versions.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
	  <Exec Command="&quot;$(ProjectDir)Properties\gen_rsc.bat&quot; &quot;$(ProjectDir)&quot;" />
	</Target>

</Project>
