//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatInspector.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatInspector.Properties.MyResources", typeof(MyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version History ähnelt.
        /// </summary>
        public static string AboutHistory {
            get {
                return ResourceManager.GetString("AboutHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        public static string BtnApply {
            get {
                return ResourceManager.GetString("BtnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load ... ähnelt.
        /// </summary>
        public static string BtnLoad {
            get {
                return ResourceManager.GetString("BtnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string BtnOK {
            get {
                return ResourceManager.GetString("BtnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run ähnelt.
        /// </summary>
        public static string BtnRun {
            get {
                return ResourceManager.GetString("BtnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save as ... ähnelt.
        /// </summary>
        public static string BtnSaveAs {
            get {
                return ResourceManager.GetString("BtnSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Call Distance ähnelt.
        /// </summary>
        public static string CallDistance {
            get {
                return ResourceManager.GetString("CallDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Call Information ähnelt.
        /// </summary>
        public static string CallInformation {
            get {
                return ResourceManager.GetString("CallInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die char. Frequency ähnelt.
        /// </summary>
        public static string CharFrequency {
            get {
                return ResourceManager.GetString("CharFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blue ähnelt.
        /// </summary>
        public static string ColorMapBlue {
            get {
                return ResourceManager.GetString("ColorMapBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color Pt ähnelt.
        /// </summary>
        public static string ColorMapColorPt {
            get {
                return ResourceManager.GetString("ColorMapColorPt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure Color Gradient ähnelt.
        /// </summary>
        public static string ColorMapConfig {
            get {
                return ResourceManager.GetString("ColorMapConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color Gradient ähnelt.
        /// </summary>
        public static string ColorMapGradient {
            get {
                return ResourceManager.GetString("ColorMapGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Green ähnelt.
        /// </summary>
        public static string ColorMapGreen {
            get {
                return ResourceManager.GetString("ColorMapGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Red ähnelt.
        /// </summary>
        public static string ColorMapRed {
            get {
                return ResourceManager.GetString("ColorMapRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value Pt ähnelt.
        /// </summary>
        public static string ColorMapValuePt {
            get {
                return ResourceManager.GetString("ColorMapValuePt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear ähnelt.
        /// </summary>
        public static string CtlLogClear {
            get {
                return ResourceManager.GetString("CtlLogClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Command: ähnelt.
        /// </summary>
        public static string CtlLogCommand {
            get {
                return ResourceManager.GetString("CtlLogCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die enter cosole command here... ähnelt.
        /// </summary>
        public static string CtlLogEnterCommandHere {
            get {
                return ResourceManager.GetString("CtlLogEnterCommandHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Created ähnelt.
        /// </summary>
        public static string ctlPrjInfoCreated {
            get {
                return ResourceManager.GetString("ctlPrjInfoCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes ähnelt.
        /// </summary>
        public static string ctlPrjInfoNotes {
            get {
                return ResourceManager.GetString("ctlPrjInfoNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Information ähnelt.
        /// </summary>
        public static string ctlProjectInfo {
            get {
                return ResourceManager.GetString("ctlProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Report ähnelt.
        /// </summary>
        public static string CtlReportCreate {
            get {
                return ResourceManager.GetString("CtlReportCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Proof of Species ähnelt.
        /// </summary>
        public static string CtlSpecProofSpecies {
            get {
                return ResourceManager.GetString("CtlSpecProofSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destination Directory ähnelt.
        /// </summary>
        public static string CtlSumReportDstDirectory {
            get {
                return ResourceManager.GetString("CtlSumReportDstDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End Date ähnelt.
        /// </summary>
        public static string CtlSumReportEndDate {
            get {
                return ResourceManager.GetString("CtlSumReportEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Root Directory ähnelt.
        /// </summary>
        public static string CtlSumReportRootDirectory {
            get {
                return ResourceManager.GetString("CtlSumReportRootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Date ähnelt.
        /// </summary>
        public static string CtlSumReportStartDate {
            get {
                return ResourceManager.GetString("CtlSumReportStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timespan ähnelt.
        /// </summary>
        public static string CtlSumReportTimespan {
            get {
                return ResourceManager.GetString("CtlSumReportTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daily ähnelt.
        /// </summary>
        public static string CtlSumReportTsDaily {
            get {
                return ResourceManager.GetString("CtlSumReportTsDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monthly ähnelt.
        /// </summary>
        public static string CtlSumReportTsMonthly {
            get {
                return ResourceManager.GetString("CtlSumReportTsMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weekly ähnelt.
        /// </summary>
        public static string CtlSumReportTsWeekly {
            get {
                return ResourceManager.GetString("CtlSumReportTsWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic Classification ähnelt.
        /// </summary>
        public static string CtlWavAutoDetection {
            get {
                return ResourceManager.GetString("CtlWavAutoDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Call ähnelt.
        /// </summary>
        public static string CtlWavCall {
            get {
                return ResourceManager.GetString("CtlWavCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual Classification ähnelt.
        /// </summary>
        public static string CtlWavManualDetection {
            get {
                return ResourceManager.GetString("CtlWavManualDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remarks ähnelt.
        /// </summary>
        public static string CtlWavRemarks {
            get {
                return ResourceManager.GetString("CtlWavRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dist to previous ähnelt.
        /// </summary>
        public static string CtlZoomDistToPrev {
            get {
                return ResourceManager.GetString("CtlZoomDistToPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Information ähnelt.
        /// </summary>
        public static string CtlZoomFileInfo {
            get {
                return ResourceManager.GetString("CtlZoomFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gain ähnelt.
        /// </summary>
        public static string CtlZoomGain {
            get {
                return ResourceManager.GetString("CtlZoomGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position ähnelt.
        /// </summary>
        public static string CtlZoomPos {
            get {
                return ResourceManager.GetString("CtlZoomPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die dyn. Range ähnelt.
        /// </summary>
        public static string CtlZoomRange {
            get {
                return ResourceManager.GetString("CtlZoomRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recording Time ähnelt.
        /// </summary>
        public static string CtlZoomRecTime {
            get {
                return ResourceManager.GetString("CtlZoomRecTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Species Auto ähnelt.
        /// </summary>
        public static string CtlZoomSpeciesAuto {
            get {
                return ResourceManager.GetString("CtlZoomSpeciesAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Species Manual ähnelt.
        /// </summary>
        public static string CtlZoomSpeciesMan {
            get {
                return ResourceManager.GetString("CtlZoomSpeciesMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trigger Filter ähnelt.
        /// </summary>
        public static string CtlZoomTrigFilt {
            get {
                return ResourceManager.GetString("CtlZoomTrigFilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trigger Filter Freq. [kHz] ähnelt.
        /// </summary>
        public static string CtlZoomTrigFilttFreq {
            get {
                return ResourceManager.GetString("CtlZoomTrigFilttFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trigger Level [dB] ähnelt.
        /// </summary>
        public static string CtlZoomTrigLevel {
            get {
                return ResourceManager.GetString("CtlZoomTrigLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom Aplitude ähnelt.
        /// </summary>
        public static string ctlZoomZoomAplitude {
            get {
                return ResourceManager.GetString("ctlZoomZoomAplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First ähnelt.
        /// </summary>
        public static string CtrlZoomFirst {
            get {
                return ResourceManager.GetString("CtrlZoomFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last ähnelt.
        /// </summary>
        public static string CtrlZoomLast {
            get {
                return ResourceManager.GetString("CtrlZoomLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mean Values Calls ähnelt.
        /// </summary>
        public static string CtrlZoomMeanValues {
            get {
                return ResourceManager.GetString("CtrlZoomMeanValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Lag ähnelt.
        /// </summary>
        public static string DeltaT {
            get {
                return ResourceManager.GetString("DeltaT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duration ähnelt.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Factory settings ähnelt.
        /// </summary>
        public static string FactorySettings {
            get {
                return ResourceManager.GetString("FactorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Narrow down species ähnelt.
        /// </summary>
        public static string FindBatNarrowDown {
            get {
                return ResourceManager.GetString("FindBatNarrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Possible Species ähnelt.
        /// </summary>
        public static string FindBatPossibleSpecies {
            get {
                return ResourceManager.GetString("FindBatPossibleSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fmax [kHz] ähnelt.
        /// </summary>
        public static string Fmax {
            get {
                return ResourceManager.GetString("Fmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FmaxAmpl [kHz] ähnelt.
        /// </summary>
        public static string fMaxAmpl {
            get {
                return ResourceManager.GetString("fMaxAmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fmin [kHz] ähnelt.
        /// </summary>
        public static string Fmin {
            get {
                return ResourceManager.GetString("Fmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frequency ähnelt.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter missing information to create XML info files for this project ähnelt.
        /// </summary>
        public static string frmCreateXmlInfo {
            get {
                return ResourceManager.GetString("frmCreateXmlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create XML Info Files ähnelt.
        /// </summary>
        public static string frmCreateXmlTitle {
            get {
                return ResourceManager.GetString("frmCreateXmlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter Expression ähnelt.
        /// </summary>
        public static string FrmFilterFilterExpression {
            get {
                return ResourceManager.GetString("FrmFilterFilterExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter Name ähnelt.
        /// </summary>
        public static string FrmFilterFilterName {
            get {
                return ResourceManager.GetString("FrmFilterFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List of available variables ähnelt.
        /// </summary>
        public static string FrmFilterListOfVars {
            get {
                return ResourceManager.GetString("FrmFilterListOfVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage Display Filter ähnelt.
        /// </summary>
        public static string FrmFilterTitle {
            get {
                return ResourceManager.GetString("FrmFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close list without changes ähnelt.
        /// </summary>
        public static string FrmFilterToolCancel {
            get {
                return ResourceManager.GetString("FrmFilterToolCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close list and save changes ähnelt.
        /// </summary>
        public static string FrmFilterToolOk {
            get {
                return ResourceManager.GetString("FrmFilterToolOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add a filter expression to the list ähnelt.
        /// </summary>
        public static string FrmFilterTtipAdd {
            get {
                return ResourceManager.GetString("FrmFilterTtipAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show list of variables available for filter expressions ähnelt.
        /// </summary>
        public static string FrmFilterTtipShowList {
            get {
                return ResourceManager.GetString("FrmFilterTtipShowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bat Species Determination, part 1 ähnelt.
        /// </summary>
        public static string FrmMainBatDetermination1 {
            get {
                return ResourceManager.GetString("FrmMainBatDetermination1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bat Species Determination, part 2 ähnelt.
        /// </summary>
        public static string FrmMainBatDetermination2 {
            get {
                return ResourceManager.GetString("FrmMainBatDetermination2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freeze Axes ähnelt.
        /// </summary>
        public static string frmMainFreezeAxes {
            get {
                return ResourceManager.GetString("frmMainFreezeAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scatter Diagram ähnelt.
        /// </summary>
        public static string frmMainScatterDiagram {
            get {
                return ResourceManager.GetString("frmMainScatterDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Software Manual ähnelt.
        /// </summary>
        public static string frmMainSoftwareManual {
            get {
                return ResourceManager.GetString("frmMainSoftwareManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-Axis: ähnelt.
        /// </summary>
        public static string frmMainXAxis {
            get {
                return ResourceManager.GetString("frmMainXAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y-Axis: ähnelt.
        /// </summary>
        public static string frmMainYAxis {
            get {
                return ResourceManager.GetString("frmMainYAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prepare data ähnelt.
        /// </summary>
        public static string frmPredPrepare {
            get {
                return ResourceManager.GetString("frmPredPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Script Description ähnelt.
        /// </summary>
        public static string FrmScriptDescription {
            get {
                return ResourceManager.GetString("FrmScriptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Script Name ähnelt.
        /// </summary>
        public static string FrmScriptName {
            get {
                return ResourceManager.GetString("FrmScriptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage, edit and execute scripts ähnelt.
        /// </summary>
        public static string FrmScriptTitle {
            get {
                return ResourceManager.GetString("FrmScriptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add a new script to the list ähnelt.
        /// </summary>
        public static string FrmScriptTtipAdd {
            get {
                return ResourceManager.GetString("FrmScriptTtipAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die delete temporary files after prediction ähnelt.
        /// </summary>
        public static string frmStartPredCleanuop {
            get {
                return ResourceManager.GetString("frmStartPredCleanuop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confidence test ähnelt.
        /// </summary>
        public static string frmStartPredConfTest {
            get {
                return ResourceManager.GetString("frmStartPredConfTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cut Calls ähnelt.
        /// </summary>
        public static string frmStartPredCut {
            get {
                return ResourceManager.GetString("frmStartPredCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Identify calls ähnelt.
        /// </summary>
        public static string frmStartPredInspect {
            get {
                return ResourceManager.GetString("frmStartPredInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This operation may take a long time, do you want to proceed? ähnelt.
        /// </summary>
        public static string frmStartPredMsg {
            get {
                return ResourceManager.GetString("frmStartPredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Predict species (classifier 1) ähnelt.
        /// </summary>
        public static string frmStartPredPredict1 {
            get {
                return ResourceManager.GetString("frmStartPredPredict1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Predict species (classifier 2) ähnelt.
        /// </summary>
        public static string frmStartPredPredict2 {
            get {
                return ResourceManager.GetString("frmStartPredPredict2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Predict species (classifier 3) ähnelt.
        /// </summary>
        public static string frmStartPredPredict3 {
            get {
                return ResourceManager.GetString("frmStartPredPredict3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adapt sampling rate ähnelt.
        /// </summary>
        public static string frmStartPredResample {
            get {
                return ResourceManager.GetString("frmStartPredResample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start automatic prediction of species ähnelt.
        /// </summary>
        public static string frmStartPredTitle {
            get {
                return ResourceManager.GetString("frmStartPredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latitude ähnelt.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latitude format error:  ähnelt.
        /// </summary>
        public static string LatitudeFormatError {
            get {
                return ResourceManager.GetString("LatitudeFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Licenses ähnelt.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Longitude ähnelt.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Longitude format error:  ähnelt.
        /// </summary>
        public static string LongitudeFormatError {
            get {
                return ResourceManager.GetString("LongitudeFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        public static string MainBtnAll {
            get {
                return ResourceManager.GetString("MainBtnAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply Filter ähnelt.
        /// </summary>
        public static string MainBtnApplyFilter {
            get {
                return ResourceManager.GetString("MainBtnApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply spec selected ähnelt.
        /// </summary>
        public static string MainBtnCopySpec {
            get {
                return ResourceManager.GetString("MainBtnCopySpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Del selected ähnelt.
        /// </summary>
        public static string MainBtnDelSelected {
            get {
                return ResourceManager.GetString("MainBtnDelSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide/Show Info ähnelt.
        /// </summary>
        public static string MainBtnHideShowInfo {
            get {
                return ResourceManager.GetString("MainBtnHideShowInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide unselected ähnelt.
        /// </summary>
        public static string MainBtnHideUnselected {
            get {
                return ResourceManager.GetString("MainBtnHideUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string MainBtnNone {
            get {
                return ResourceManager.GetString("MainBtnNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show all ähnelt.
        /// </summary>
        public static string MainBtnShowAll {
            get {
                return ResourceManager.GetString("MainBtnShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size ähnelt.
        /// </summary>
        public static string MainBtnSize {
            get {
                return ResourceManager.GetString("MainBtnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter:  ähnelt.
        /// </summary>
        public static string MainFilter {
            get {
                return ResourceManager.GetString("MainFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string MainFilterNone {
            get {
                return ResourceManager.GetString("MainFilterNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report Project ähnelt.
        /// </summary>
        public static string MainReportProject {
            get {
                return ResourceManager.GetString("MainReportProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report Timespan ähnelt.
        /// </summary>
        public static string MainReportTimespan {
            get {
                return ResourceManager.GetString("MainReportTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Folder ähnelt.
        /// </summary>
        public static string MainSelectFolder {
            get {
                return ResourceManager.GetString("MainSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel running script ähnelt.
        /// </summary>
        public static string MainToolCancelScript {
            get {
                return ResourceManager.GetString("MainToolCancelScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create summarized report ähnelt.
        /// </summary>
        public static string MainToolCreateSumReport {
            get {
                return ResourceManager.GetString("MainToolCreateSumReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define filters for lists ähnelt.
        /// </summary>
        public static string MainToolDefFilters {
            get {
                return ResourceManager.GetString("MainToolDefFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit application settings ähnelt.
        /// </summary>
        public static string MainToolEditAppSettings {
            get {
                return ResourceManager.GetString("MainToolEditAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit color scheme for waterfall diagram ähnelt.
        /// </summary>
        public static string MainToolEditColorScheme {
            get {
                return ResourceManager.GetString("MainToolEditColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit species information ähnelt.
        /// </summary>
        public static string MainToolEditSpeciesInfo {
            get {
                return ResourceManager.GetString("MainToolEditSpeciesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Evaluate and classify bat calls in project ähnelt.
        /// </summary>
        public static string MainToolEvalBatCalls {
            get {
                return ResourceManager.GetString("MainToolEvalBatCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find species by entering call parameters ähnelt.
        /// </summary>
        public static string MainToolFindSpeciesInfo {
            get {
                return ResourceManager.GetString("MainToolFindSpeciesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate xml information files for current project ähnelt.
        /// </summary>
        public static string MainToolGenXmlFiles {
            get {
                return ResourceManager.GetString("MainToolGenXmlFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inspect and manipulate wav files ähnelt.
        /// </summary>
        public static string MainToolManipWavFiles {
            get {
                return ResourceManager.GetString("MainToolManipWavFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open manual ähnelt.
        /// </summary>
        public static string MainToolOpenManual {
            get {
                return ResourceManager.GetString("MainToolOpenManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh views ähnelt.
        /// </summary>
        public static string MainToolRefresh {
            get {
                return ResourceManager.GetString("MainToolRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Report ähnelt.
        /// </summary>
        public static string MainToolReport {
            get {
                return ResourceManager.GetString("MainToolReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run script ähnelt.
        /// </summary>
        public static string MainToolRunScript {
            get {
                return ResourceManager.GetString("MainToolRunScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show software info ähnelt.
        /// </summary>
        public static string MainToolShowSoftwareInfo {
            get {
                return ResourceManager.GetString("MainToolShowSoftwareInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Training Data ähnelt.
        /// </summary>
        public static string MainTrainData {
            get {
                return ResourceManager.GetString("MainTrainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project View ähnelt.
        /// </summary>
        public static string MainWinProjectView {
            get {
                return ResourceManager.GetString("MainWinProjectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fmax ähnelt.
        /// </summary>
        public static string MaxFrequency {
            get {
                return ResourceManager.GetString("MaxFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fmin ähnelt.
        /// </summary>
        public static string MinFrequency {
            get {
                return ResourceManager.GetString("MinFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete all selected files? ähnelt.
        /// </summary>
        public static string msgDeleteFiles {
            get {
                return ResourceManager.GetString("msgDeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to reset to factory settings? ähnelt.
        /// </summary>
        public static string msgFactorySettings {
            get {
                return ResourceManager.GetString("msgFactorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string msgInformation {
            get {
                return ResourceManager.GetString("msgInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        public static string msgQuestion {
            get {
                return ResourceManager.GetString("msgQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to save changed project before closing? ähnelt.
        /// </summary>
        public static string msgSaveBeforeClose {
            get {
                return ResourceManager.GetString("msgSaveBeforeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable both cursors first! ähnelt.
        /// </summary>
        public static string msgZoomNotPossible {
            get {
                return ResourceManager.GetString("msgZoomNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Point in Time ähnelt.
        /// </summary>
        public static string PointInTime {
            get {
                return ResourceManager.GetString("PointInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sampling Rate ähnelt.
        /// </summary>
        public static string SamplingRate {
            get {
                return ResourceManager.GetString("SamplingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die select call type ähnelt.
        /// </summary>
        public static string SelectCallType {
            get {
                return ResourceManager.GetString("SelectCallType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide call related information in overview ähnelt.
        /// </summary>
        public static string SerDescHideCallInfo {
            get {
                return ResourceManager.GetString("SerDescHideCallInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application ähnelt.
        /// </summary>
        public static string SetCatApplication {
            get {
                return ResourceManager.GetString("SetCatApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bat Species ähnelt.
        /// </summary>
        public static string SetCatBatSpecies {
            get {
                return ResourceManager.GetString("SetCatBatSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color Gradient ähnelt.
        /// </summary>
        public static string SetCatColorGradient {
            get {
                return ResourceManager.GetString("SetCatColorGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Model ähnelt.
        /// </summary>
        public static string SetCatModel {
            get {
                return ResourceManager.GetString("SetCatModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prediction ähnelt.
        /// </summary>
        public static string SetCatPrediction {
            get {
                return ResourceManager.GetString("SetCatPrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scripting ähnelt.
        /// </summary>
        public static string SetCatScripting {
            get {
                return ResourceManager.GetString("SetCatScripting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for bat species ähnelt.
        /// </summary>
        public static string SetDescBatSpecies {
            get {
                return ResourceManager.GetString("SetDescBatSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color of Background in XT diagram ähnelt.
        /// </summary>
        public static string SetDescColorBackgXTDiag {
            get {
                return ResourceManager.GetString("SetDescColorBackgXTDiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color of line in XT diagram ähnelt.
        /// </summary>
        public static string SetDescColorOfLine {
            get {
                return ResourceManager.GetString("SetDescColorOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nr of epochs during training of model ähnelt.
        /// </summary>
        public static string SetDescEpochs {
            get {
                return ResourceManager.GetString("SetDescEpochs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for display filter ähnelt.
        /// </summary>
        public static string SetDescFilter {
            get {
                return ResourceManager.GetString("SetDescFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height of log control [px] ähnelt.
        /// </summary>
        public static string SetDescHeightLogCtrl {
            get {
                return ResourceManager.GetString("SetDescHeightLogCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height of main window [px] ähnelt.
        /// </summary>
        public static string SetDescHeightMainWin {
            get {
                return ResourceManager.GetString("SetDescHeightMainWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height of waterfall diagram in pixel ähnelt.
        /// </summary>
        public static string SetDescHeightWf {
            get {
                return ResourceManager.GetString("SetDescHeightWf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set language ähnelt.
        /// </summary>
        public static string SetDescLanguage {
            get {
                return ResourceManager.GetString("SetDescLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set the learning rate to train the model ähnelt.
        /// </summary>
        public static string SetDescLearningRate {
            get {
                return ResourceManager.GetString("SetDescLearningRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Length of zoom for automatic zoom to call [ms] ähnelt.
        /// </summary>
        public static string SetDescLengthZoomMs {
            get {
                return ResourceManager.GetString("SetDescLengthZoomMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main window X position ähnelt.
        /// </summary>
        public static string SetDescMainWinPosX {
            get {
                return ResourceManager.GetString("SetDescMainWinPosX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main window y position ähnelt.
        /// </summary>
        public static string SetDescMainWinPosY {
            get {
                return ResourceManager.GetString("SetDescMainWinPosY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Full path to root directory containing the trained AI  models ähnelt.
        /// </summary>
        public static string SetDescModDir {
            get {
                return ResourceManager.GetString("SetDescModDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimal probability to copy automated to manually set probability with copy button ähnelt.
        /// </summary>
        public static string SetDescProb {
            get {
                return ResourceManager.GetString("SetDescProb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Full path to python executable for executing python scripts ähnelt.
        /// </summary>
        public static string SetDescPythonExe {
            get {
                return ResourceManager.GetString("SetDescPythonExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Range for color gradient in zoom window [dB] ähnelt.
        /// </summary>
        public static string SetDescRangeZoomWin {
            get {
                return ResourceManager.GetString("SetDescRangeZoomWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of column in report for automatically detected species ähnelt.
        /// </summary>
        public static string SetDescReportColumn {
            get {
                return ResourceManager.GetString("SetDescReportColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Root path of application ähnelt.
        /// </summary>
        public static string SetDescRootPath {
            get {
                return ResourceManager.GetString("SetDescRootPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sampling rate needed for AI models ähnelt.
        /// </summary>
        public static string SetDescSamplingRate {
            get {
                return ResourceManager.GetString("SetDescSamplingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die full path to python script to predict bat species ähnelt.
        /// </summary>
        public static string SetDescScriptPredict {
            get {
                return ResourceManager.GetString("SetDescScriptPredict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die full path to R script for determination of call parameters ähnelt.
        /// </summary>
        public static string SetDescScriptProp {
            get {
                return ResourceManager.GetString("SetDescScriptProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Csv file containing list of species supported by automatic species detection ähnelt.
        /// </summary>
        public static string SetDescSpeciesFile {
            get {
                return ResourceManager.GetString("SetDescSpeciesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define if waterfall diagram should be logarithmic or linear ähnelt.
        /// </summary>
        public static string SetDescWfLog {
            get {
                return ResourceManager.GetString("SetDescWfLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width of FFT in points (MUST be a power of 2) ähnelt.
        /// </summary>
        public static string SetDescWidthFFT {
            get {
                return ResourceManager.GetString("SetDescWidthFFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width of file browser [px] ähnelt.
        /// </summary>
        public static string SetDescWidthFileSel {
            get {
                return ResourceManager.GetString("SetDescWidthFileSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width of main window [px] ähnelt.
        /// </summary>
        public static string SetDescWidthMainWin {
            get {
                return ResourceManager.GetString("SetDescWidthMainWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application ähnelt.
        /// </summary>
        public static string SettingsApplication {
            get {
                return ResourceManager.GetString("SettingsApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S/N ratio ähnelt.
        /// </summary>
        public static string Snr {
            get {
                return ResourceManager.GetString("Snr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4 letter abbreviation for species name ähnelt.
        /// </summary>
        public static string SpecDescAbbr {
            get {
                return ResourceManager.GetString("SpecDescAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adapt sample rate to trained model ähnelt.
        /// </summary>
        public static string SpecDescAdapt {
            get {
                return ResourceManager.GetString("SpecDescAdapt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Definition of color gradient for color channel blue ähnelt.
        /// </summary>
        public static string SpecDescColorBlue {
            get {
                return ResourceManager.GetString("SpecDescColorBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Definition of color gradient for color channel green ähnelt.
        /// </summary>
        public static string SpecDescColorGreen {
            get {
                return ResourceManager.GetString("SpecDescColorGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Definition of color gradient for color channel red ähnelt.
        /// </summary>
        public static string SpecDescColorRed {
            get {
                return ResourceManager.GetString("SpecDescColorRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die execute confidence test ähnelt.
        /// </summary>
        public static string SpecDescConfTest {
            get {
                return ResourceManager.GetString("SpecDescConfTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cut recordings to single calls ähnelt.
        /// </summary>
        public static string SpecDescCutCalls {
            get {
                return ResourceManager.GetString("SpecDescCutCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete temporary files (wav and data) ähnelt.
        /// </summary>
        public static string SpecDescDelTemp {
            get {
                return ResourceManager.GetString("SpecDescDelTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die identify calls and their parameters ähnelt.
        /// </summary>
        public static string SpecDescIdentify {
            get {
                return ResourceManager.GetString("SpecDescIdentify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latin species name ähnelt.
        /// </summary>
        public static string SpecDescLatinSpec {
            get {
                return ResourceManager.GetString("SpecDescLatinSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximal call duration [ms] ähnelt.
        /// </summary>
        public static string SpecDescMaxCall {
            get {
                return ResourceManager.GetString("SpecDescMaxCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximal call diatance [ms] ähnelt.
        /// </summary>
        public static string SpecDescMaxCallDist {
            get {
                return ResourceManager.GetString("SpecDescMaxCallDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimal call duration [ms] ähnelt.
        /// </summary>
        public static string SpecDescMinCall {
            get {
                return ResourceManager.GetString("SpecDescMinCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimal call diatance [ms] ähnelt.
        /// </summary>
        public static string SpecDescMinCallDist {
            get {
                return ResourceManager.GetString("SpecDescMinCallDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Execute species prediciton ähnelt.
        /// </summary>
        public static string SpecDescPredict {
            get {
                return ResourceManager.GetString("SpecDescPredict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prepare data fro prediciton ähnelt.
        /// </summary>
        public static string SpecDescPrepData {
            get {
                return ResourceManager.GetString("SpecDescPrepData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show species in comboboxes to select species ähnelt.
        /// </summary>
        public static string SpecDescShowSpec {
            get {
                return ResourceManager.GetString("SpecDescShowSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show zoom view in a separate window side by side to main window ähnelt.
        /// </summary>
        public static string SpecDescShowZoom {
            get {
                return ResourceManager.GetString("SpecDescShowZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die full path to Wav example file ähnelt.
        /// </summary>
        public static string SpecDescWav {
            get {
                return ResourceManager.GetString("SpecDescWav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width of waterfall diagram in pixel ähnelt.
        /// </summary>
        public static string SpecDescWidthWf {
            get {
                return ResourceManager.GetString("SpecDescWidthWf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die decrease dynamic range ähnelt.
        /// </summary>
        public static string ToolTipDecRange {
            get {
                return ResourceManager.GetString("ToolTipDecRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die increase dynamic range ähnelt.
        /// </summary>
        public static string ToolTipIncRange {
            get {
                return ResourceManager.GetString("ToolTipIncRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move down (decreasing frequency) ähnelt.
        /// </summary>
        public static string ToolTipMoveDownF {
            get {
                return ResourceManager.GetString("ToolTipMoveDownF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move left (decreasing time) ähnelt.
        /// </summary>
        public static string ToolTipMoveLeftT {
            get {
                return ResourceManager.GetString("ToolTipMoveLeftT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move right (increasing time) ähnelt.
        /// </summary>
        public static string ToolTipMoveRightIT {
            get {
                return ResourceManager.GetString("ToolTipMoveRightIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move up (increasing frequency) ähnelt.
        /// </summary>
        public static string ToolTipMoveUpF {
            get {
                return ResourceManager.GetString("ToolTipMoveUpF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die play displayed section ähnelt.
        /// </summary>
        public static string ToolTipPlayDispSection {
            get {
                return ResourceManager.GetString("ToolTipPlayDispSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die play displayed section, stretched 10x ähnelt.
        /// </summary>
        public static string ToolTipPlayDispSection10x {
            get {
                return ResourceManager.GetString("ToolTipPlayDispSection10x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die play displayed section, stretched 20x ähnelt.
        /// </summary>
        public static string ToolTipPlayDispSection20x {
            get {
                return ResourceManager.GetString("ToolTipPlayDispSection20x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die save settings ähnelt.
        /// </summary>
        public static string ToolTipSaveSettings {
            get {
                return ResourceManager.GetString("ToolTipSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die stop playing audio ähnelt.
        /// </summary>
        public static string ToolTipStopPlayingAudio {
            get {
                return ResourceManager.GetString("ToolTipStopPlayingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom in x2 horizontally ähnelt.
        /// </summary>
        public static string ToolTipZoomInX2H {
            get {
                return ResourceManager.GetString("ToolTipZoomInX2H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom in x2 vertically ähnelt.
        /// </summary>
        public static string TooltipZoomInX2V {
            get {
                return ResourceManager.GetString("TooltipZoomInX2V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom out to total image ähnelt.
        /// </summary>
        public static string ToolTipZoomOutTotal {
            get {
                return ResourceManager.GetString("ToolTipZoomOutTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom out x2 horizontally ähnelt.
        /// </summary>
        public static string ToolTipZoomOutX2Horizontally {
            get {
                return ResourceManager.GetString("ToolTipZoomOutX2Horizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom out x2 vertically ähnelt.
        /// </summary>
        public static string ToolTipZoomOutX2V {
            get {
                return ResourceManager.GetString("ToolTipZoomOutX2V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom to cursor ähnelt.
        /// </summary>
        public static string ToolTipZoomToCursor {
            get {
                return ResourceManager.GetString("ToolTipZoomToCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
