//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatInspector.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatInspector.Properties.MyResources", typeof(MyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version History ähnelt.
        /// </summary>
        public static string AboutHistory {
            get {
                return ResourceManager.GetString("AboutHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        public static string BtnApply {
            get {
                return ResourceManager.GetString("BtnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Call Information ähnelt.
        /// </summary>
        public static string CallInformation {
            get {
                return ResourceManager.GetString("CallInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die char. Frequency ähnelt.
        /// </summary>
        public static string CharFrequency {
            get {
                return ResourceManager.GetString("CharFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blue ähnelt.
        /// </summary>
        public static string ColorMapBlue {
            get {
                return ResourceManager.GetString("ColorMapBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color Pt ähnelt.
        /// </summary>
        public static string ColorMapColorPt {
            get {
                return ResourceManager.GetString("ColorMapColorPt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure Color Gradient ähnelt.
        /// </summary>
        public static string ColorMapConfig {
            get {
                return ResourceManager.GetString("ColorMapConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color Gradient ähnelt.
        /// </summary>
        public static string ColorMapGradient {
            get {
                return ResourceManager.GetString("ColorMapGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Green ähnelt.
        /// </summary>
        public static string ColorMapGreen {
            get {
                return ResourceManager.GetString("ColorMapGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Red ähnelt.
        /// </summary>
        public static string ColorMapRed {
            get {
                return ResourceManager.GetString("ColorMapRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value Pt ähnelt.
        /// </summary>
        public static string ColorMapValuePt {
            get {
                return ResourceManager.GetString("ColorMapValuePt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear ähnelt.
        /// </summary>
        public static string CtlLogClear {
            get {
                return ResourceManager.GetString("CtlLogClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic Classification ähnelt.
        /// </summary>
        public static string CtlWavAutoDetection {
            get {
                return ResourceManager.GetString("CtlWavAutoDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Call ähnelt.
        /// </summary>
        public static string CtlWavCall {
            get {
                return ResourceManager.GetString("CtlWavCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual Classification ähnelt.
        /// </summary>
        public static string CtlWavManualDetection {
            get {
                return ResourceManager.GetString("CtlWavManualDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remarks ähnelt.
        /// </summary>
        public static string CtlWavRemarks {
            get {
                return ResourceManager.GetString("CtlWavRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dist to previous ähnelt.
        /// </summary>
        public static string CtlZoomDistToPrev {
            get {
                return ResourceManager.GetString("CtlZoomDistToPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die dyn. Range ähnelt.
        /// </summary>
        public static string CtlZoomRange {
            get {
                return ResourceManager.GetString("CtlZoomRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Lag ähnelt.
        /// </summary>
        public static string DeltaT {
            get {
                return ResourceManager.GetString("DeltaT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duration ähnelt.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Factory settings ähnelt.
        /// </summary>
        public static string FactorySettings {
            get {
                return ResourceManager.GetString("FactorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frequency ähnelt.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Licenses ähnelt.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        public static string MainBtnAll {
            get {
                return ResourceManager.GetString("MainBtnAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply Filter ähnelt.
        /// </summary>
        public static string MainBtnApplyFilter {
            get {
                return ResourceManager.GetString("MainBtnApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Del selected ähnelt.
        /// </summary>
        public static string MainBtnDelSelected {
            get {
                return ResourceManager.GetString("MainBtnDelSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide/Show Info ähnelt.
        /// </summary>
        public static string MainBtnHideShowInfo {
            get {
                return ResourceManager.GetString("MainBtnHideShowInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide unselected ähnelt.
        /// </summary>
        public static string MainBtnHideUnselected {
            get {
                return ResourceManager.GetString("MainBtnHideUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string MainBtnNone {
            get {
                return ResourceManager.GetString("MainBtnNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show all ähnelt.
        /// </summary>
        public static string MainBtnShowAll {
            get {
                return ResourceManager.GetString("MainBtnShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size ähnelt.
        /// </summary>
        public static string MainBtnSize {
            get {
                return ResourceManager.GetString("MainBtnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter:  ähnelt.
        /// </summary>
        public static string MainFilter {
            get {
                return ResourceManager.GetString("MainFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project View ähnelt.
        /// </summary>
        public static string MainWinProjectView {
            get {
                return ResourceManager.GetString("MainWinProjectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Point in Time ähnelt.
        /// </summary>
        public static string PointInTime {
            get {
                return ResourceManager.GetString("PointInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sampling Rate ähnelt.
        /// </summary>
        public static string SamplingRate {
            get {
                return ResourceManager.GetString("SamplingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die select call type ähnelt.
        /// </summary>
        public static string SelectCallType {
            get {
                return ResourceManager.GetString("SelectCallType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S/N ratio ähnelt.
        /// </summary>
        public static string Snr {
            get {
                return ResourceManager.GetString("Snr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die decrease dynamic range ähnelt.
        /// </summary>
        public static string ToolTipDecRange {
            get {
                return ResourceManager.GetString("ToolTipDecRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die increase dynamic range ähnelt.
        /// </summary>
        public static string ToolTipIncRange {
            get {
                return ResourceManager.GetString("ToolTipIncRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move down (decreasing frequency) ähnelt.
        /// </summary>
        public static string ToolTipMoveDownF {
            get {
                return ResourceManager.GetString("ToolTipMoveDownF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move left (decreasing time) ähnelt.
        /// </summary>
        public static string ToolTipMoveLeftT {
            get {
                return ResourceManager.GetString("ToolTipMoveLeftT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move right (increasing time) ähnelt.
        /// </summary>
        public static string ToolTipMoveRightIT {
            get {
                return ResourceManager.GetString("ToolTipMoveRightIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move up (increasing frequency) ähnelt.
        /// </summary>
        public static string ToolTipMoveUpF {
            get {
                return ResourceManager.GetString("ToolTipMoveUpF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die play displayed section ähnelt.
        /// </summary>
        public static string ToolTipPlayDispSection {
            get {
                return ResourceManager.GetString("ToolTipPlayDispSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die play displayed section, stretched 10x ähnelt.
        /// </summary>
        public static string ToolTipPlayDispSection10x {
            get {
                return ResourceManager.GetString("ToolTipPlayDispSection10x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die play displayed section, stretched 20x ähnelt.
        /// </summary>
        public static string ToolTipPlayDispSection20x {
            get {
                return ResourceManager.GetString("ToolTipPlayDispSection20x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die save settings ähnelt.
        /// </summary>
        public static string ToolTipSaveSettings {
            get {
                return ResourceManager.GetString("ToolTipSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die stop playing audio ähnelt.
        /// </summary>
        public static string ToolTipStopPlayingAudio {
            get {
                return ResourceManager.GetString("ToolTipStopPlayingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom in x2 horizontally ähnelt.
        /// </summary>
        public static string ToolTipZoomInX2H {
            get {
                return ResourceManager.GetString("ToolTipZoomInX2H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom in x2 vertically ähnelt.
        /// </summary>
        public static string TooltipZoomInX2V {
            get {
                return ResourceManager.GetString("TooltipZoomInX2V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom out to total image ähnelt.
        /// </summary>
        public static string ToolTipZoomOutTotal {
            get {
                return ResourceManager.GetString("ToolTipZoomOutTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom out x2 horizontally ähnelt.
        /// </summary>
        public static string ToolTipZoomOutX2Horizontally {
            get {
                return ResourceManager.GetString("ToolTipZoomOutX2Horizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom out x2 vertically ähnelt.
        /// </summary>
        public static string ToolTipZoomOutX2V {
            get {
                return ResourceManager.GetString("ToolTipZoomOutX2V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom to cursor ähnelt.
        /// </summary>
        public static string ToolTipZoomToCursor {
            get {
                return ResourceManager.GetString("ToolTipZoomToCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
