//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatInspector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatInspector.Properties.MyResources", typeof(MyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version History.
        /// </summary>
        public static string AboutHistory {
            get {
                return ResourceManager.GetString("AboutHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string BtnApply {
            get {
                return ResourceManager.GetString("BtnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string BtnOK {
            get {
                return ResourceManager.GetString("BtnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string BtnRun {
            get {
                return ResourceManager.GetString("BtnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Distance.
        /// </summary>
        public static string CallDistance {
            get {
                return ResourceManager.GetString("CallDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Information.
        /// </summary>
        public static string CallInformation {
            get {
                return ResourceManager.GetString("CallInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to char. Frequency.
        /// </summary>
        public static string CharFrequency {
            get {
                return ResourceManager.GetString("CharFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string ColorMapBlue {
            get {
                return ResourceManager.GetString("ColorMapBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Pt.
        /// </summary>
        public static string ColorMapColorPt {
            get {
                return ResourceManager.GetString("ColorMapColorPt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Color Gradient.
        /// </summary>
        public static string ColorMapConfig {
            get {
                return ResourceManager.GetString("ColorMapConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Gradient.
        /// </summary>
        public static string ColorMapGradient {
            get {
                return ResourceManager.GetString("ColorMapGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string ColorMapGreen {
            get {
                return ResourceManager.GetString("ColorMapGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string ColorMapRed {
            get {
                return ResourceManager.GetString("ColorMapRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Pt.
        /// </summary>
        public static string ColorMapValuePt {
            get {
                return ResourceManager.GetString("ColorMapValuePt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string CtlLogClear {
            get {
                return ResourceManager.GetString("CtlLogClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command:.
        /// </summary>
        public static string CtlLogCommand {
            get {
                return ResourceManager.GetString("CtlLogCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter cosole command here....
        /// </summary>
        public static string CtlLogEnterCommandHere {
            get {
                return ResourceManager.GetString("CtlLogEnterCommandHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string ctlPrjInfoCreated {
            get {
                return ResourceManager.GetString("ctlPrjInfoCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string ctlPrjInfoNotes {
            get {
                return ResourceManager.GetString("ctlPrjInfoNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Information.
        /// </summary>
        public static string ctlProjectInfo {
            get {
                return ResourceManager.GetString("ctlProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Report.
        /// </summary>
        public static string CtlReportCreate {
            get {
                return ResourceManager.GetString("CtlReportCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of Species.
        /// </summary>
        public static string CtlSpecProofSpecies {
            get {
                return ResourceManager.GetString("CtlSpecProofSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Directory.
        /// </summary>
        public static string CtlSumReportDstDirectory {
            get {
                return ResourceManager.GetString("CtlSumReportDstDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string CtlSumReportEndDate {
            get {
                return ResourceManager.GetString("CtlSumReportEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Directory.
        /// </summary>
        public static string CtlSumReportRootDirectory {
            get {
                return ResourceManager.GetString("CtlSumReportRootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string CtlSumReportStartDate {
            get {
                return ResourceManager.GetString("CtlSumReportStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timespan.
        /// </summary>
        public static string CtlSumReportTimespan {
            get {
                return ResourceManager.GetString("CtlSumReportTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string CtlSumReportTsDaily {
            get {
                return ResourceManager.GetString("CtlSumReportTsDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string CtlSumReportTsMonthly {
            get {
                return ResourceManager.GetString("CtlSumReportTsMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string CtlSumReportTsWeekly {
            get {
                return ResourceManager.GetString("CtlSumReportTsWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Classification.
        /// </summary>
        public static string CtlWavAutoDetection {
            get {
                return ResourceManager.GetString("CtlWavAutoDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string CtlWavCall {
            get {
                return ResourceManager.GetString("CtlWavCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Classification.
        /// </summary>
        public static string CtlWavManualDetection {
            get {
                return ResourceManager.GetString("CtlWavManualDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string CtlWavRemarks {
            get {
                return ResourceManager.GetString("CtlWavRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dist to previous.
        /// </summary>
        public static string CtlZoomDistToPrev {
            get {
                return ResourceManager.GetString("CtlZoomDistToPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Information.
        /// </summary>
        public static string CtlZoomFileInfo {
            get {
                return ResourceManager.GetString("CtlZoomFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain.
        /// </summary>
        public static string CtlZoomGain {
            get {
                return ResourceManager.GetString("CtlZoomGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string CtlZoomPos {
            get {
                return ResourceManager.GetString("CtlZoomPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dyn. Range.
        /// </summary>
        public static string CtlZoomRange {
            get {
                return ResourceManager.GetString("CtlZoomRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Time.
        /// </summary>
        public static string CtlZoomRecTime {
            get {
                return ResourceManager.GetString("CtlZoomRecTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species Auto.
        /// </summary>
        public static string CtlZoomSpeciesAuto {
            get {
                return ResourceManager.GetString("CtlZoomSpeciesAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species Manual.
        /// </summary>
        public static string CtlZoomSpeciesMan {
            get {
                return ResourceManager.GetString("CtlZoomSpeciesMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Filter.
        /// </summary>
        public static string CtlZoomTrigFilt {
            get {
                return ResourceManager.GetString("CtlZoomTrigFilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Filter Freq. [kHz].
        /// </summary>
        public static string CtlZoomTrigFilttFreq {
            get {
                return ResourceManager.GetString("CtlZoomTrigFilttFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Level [dB].
        /// </summary>
        public static string CtlZoomTrigLevel {
            get {
                return ResourceManager.GetString("CtlZoomTrigLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Aplitude.
        /// </summary>
        public static string ctlZoomZoomAplitude {
            get {
                return ResourceManager.GetString("ctlZoomZoomAplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string CtrlZoomFirst {
            get {
                return ResourceManager.GetString("CtrlZoomFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string CtrlZoomLast {
            get {
                return ResourceManager.GetString("CtrlZoomLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean Values Calls.
        /// </summary>
        public static string CtrlZoomMeanValues {
            get {
                return ResourceManager.GetString("CtrlZoomMeanValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Lag.
        /// </summary>
        public static string DeltaT {
            get {
                return ResourceManager.GetString("DeltaT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory settings.
        /// </summary>
        public static string FactorySettings {
            get {
                return ResourceManager.GetString("FactorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrow down species.
        /// </summary>
        public static string FindBatNarrowDown {
            get {
                return ResourceManager.GetString("FindBatNarrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible Species.
        /// </summary>
        public static string FindBatPossibleSpecies {
            get {
                return ResourceManager.GetString("FindBatPossibleSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fmax [kHz].
        /// </summary>
        public static string Fmax {
            get {
                return ResourceManager.GetString("Fmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FmaxAmpl [kHz].
        /// </summary>
        public static string fMaxAmpl {
            get {
                return ResourceManager.GetString("fMaxAmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fmin [kHz].
        /// </summary>
        public static string Fmin {
            get {
                return ResourceManager.GetString("Fmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter missing information to create XML info files for this project.
        /// </summary>
        public static string frmCreateXmlInfo {
            get {
                return ResourceManager.GetString("frmCreateXmlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create XML Info Files.
        /// </summary>
        public static string frmCreateXmlTitle {
            get {
                return ResourceManager.GetString("frmCreateXmlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Expression.
        /// </summary>
        public static string FrmFilterFilterExpression {
            get {
                return ResourceManager.GetString("FrmFilterFilterExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Name.
        /// </summary>
        public static string FrmFilterFilterName {
            get {
                return ResourceManager.GetString("FrmFilterFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of available variables.
        /// </summary>
        public static string FrmFilterListOfVars {
            get {
                return ResourceManager.GetString("FrmFilterListOfVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Display Filter.
        /// </summary>
        public static string FrmFilterTitle {
            get {
                return ResourceManager.GetString("FrmFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close list without changes.
        /// </summary>
        public static string FrmFilterToolCancel {
            get {
                return ResourceManager.GetString("FrmFilterToolCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close list and save changes.
        /// </summary>
        public static string FrmFilterToolOk {
            get {
                return ResourceManager.GetString("FrmFilterToolOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a filter expression to the list.
        /// </summary>
        public static string FrmFilterTtipAdd {
            get {
                return ResourceManager.GetString("FrmFilterTtipAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show list of variables available for filter expressions.
        /// </summary>
        public static string FrmFilterTtipShowList {
            get {
                return ResourceManager.GetString("FrmFilterTtipShowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bat Species Determination, part 1.
        /// </summary>
        public static string FrmMainBatDetermination1 {
            get {
                return ResourceManager.GetString("FrmMainBatDetermination1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bat Species Determination, part 2.
        /// </summary>
        public static string FrmMainBatDetermination2 {
            get {
                return ResourceManager.GetString("FrmMainBatDetermination2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Axes.
        /// </summary>
        public static string frmMainFreezeAxes {
            get {
                return ResourceManager.GetString("frmMainFreezeAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter Diagram.
        /// </summary>
        public static string frmMainScatterDiagram {
            get {
                return ResourceManager.GetString("frmMainScatterDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Manual.
        /// </summary>
        public static string frmMainSoftwareManual {
            get {
                return ResourceManager.GetString("frmMainSoftwareManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Axis:.
        /// </summary>
        public static string frmMainXAxis {
            get {
                return ResourceManager.GetString("frmMainXAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-Axis:.
        /// </summary>
        public static string frmMainYAxis {
            get {
                return ResourceManager.GetString("frmMainYAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare data.
        /// </summary>
        public static string frmPredPrepare {
            get {
                return ResourceManager.GetString("frmPredPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Description.
        /// </summary>
        public static string FrmScriptDescription {
            get {
                return ResourceManager.GetString("FrmScriptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Name.
        /// </summary>
        public static string FrmScriptName {
            get {
                return ResourceManager.GetString("FrmScriptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage, edit and execute scripts.
        /// </summary>
        public static string FrmScriptTitle {
            get {
                return ResourceManager.GetString("FrmScriptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a new script to the list.
        /// </summary>
        public static string FrmScriptTtipAdd {
            get {
                return ResourceManager.GetString("FrmScriptTtipAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete temporary files after prediction.
        /// </summary>
        public static string frmStartPredCleanuop {
            get {
                return ResourceManager.GetString("frmStartPredCleanuop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence test.
        /// </summary>
        public static string frmStartPredConfTest {
            get {
                return ResourceManager.GetString("frmStartPredConfTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Calls.
        /// </summary>
        public static string frmStartPredCut {
            get {
                return ResourceManager.GetString("frmStartPredCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify calls.
        /// </summary>
        public static string frmStartPredInspect {
            get {
                return ResourceManager.GetString("frmStartPredInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation may take a long time, do you want to proceed?.
        /// </summary>
        public static string frmStartPredMsg {
            get {
                return ResourceManager.GetString("frmStartPredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict species (classifier 1).
        /// </summary>
        public static string frmStartPredPredict1 {
            get {
                return ResourceManager.GetString("frmStartPredPredict1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict species (classifier 2).
        /// </summary>
        public static string frmStartPredPredict2 {
            get {
                return ResourceManager.GetString("frmStartPredPredict2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict species (classifier 3).
        /// </summary>
        public static string frmStartPredPredict3 {
            get {
                return ResourceManager.GetString("frmStartPredPredict3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapt sampling rate.
        /// </summary>
        public static string frmStartPredResample {
            get {
                return ResourceManager.GetString("frmStartPredResample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start automatic prediction of species.
        /// </summary>
        public static string frmStartPredTitle {
            get {
                return ResourceManager.GetString("frmStartPredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude format error: .
        /// </summary>
        public static string LatitudeFormatError {
            get {
                return ResourceManager.GetString("LatitudeFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude format error: .
        /// </summary>
        public static string LongitudeFormatError {
            get {
                return ResourceManager.GetString("LongitudeFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string MainBtnAll {
            get {
                return ResourceManager.GetString("MainBtnAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filter.
        /// </summary>
        public static string MainBtnApplyFilter {
            get {
                return ResourceManager.GetString("MainBtnApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply spec selected.
        /// </summary>
        public static string MainBtnCopySpec {
            get {
                return ResourceManager.GetString("MainBtnCopySpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del selected.
        /// </summary>
        public static string MainBtnDelSelected {
            get {
                return ResourceManager.GetString("MainBtnDelSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide/Show Info.
        /// </summary>
        public static string MainBtnHideShowInfo {
            get {
                return ResourceManager.GetString("MainBtnHideShowInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide unselected.
        /// </summary>
        public static string MainBtnHideUnselected {
            get {
                return ResourceManager.GetString("MainBtnHideUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string MainBtnNone {
            get {
                return ResourceManager.GetString("MainBtnNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string MainBtnShowAll {
            get {
                return ResourceManager.GetString("MainBtnShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string MainBtnSize {
            get {
                return ResourceManager.GetString("MainBtnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter: .
        /// </summary>
        public static string MainFilter {
            get {
                return ResourceManager.GetString("MainFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string MainFilterNone {
            get {
                return ResourceManager.GetString("MainFilterNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Project.
        /// </summary>
        public static string MainReportProject {
            get {
                return ResourceManager.GetString("MainReportProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Timespan.
        /// </summary>
        public static string MainReportTimespan {
            get {
                return ResourceManager.GetString("MainReportTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string MainSelectFolder {
            get {
                return ResourceManager.GetString("MainSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel running script.
        /// </summary>
        public static string MainToolCancelScript {
            get {
                return ResourceManager.GetString("MainToolCancelScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create summarized report.
        /// </summary>
        public static string MainToolCreateSumReport {
            get {
                return ResourceManager.GetString("MainToolCreateSumReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define filters for lists.
        /// </summary>
        public static string MainToolDefFilters {
            get {
                return ResourceManager.GetString("MainToolDefFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit application settings.
        /// </summary>
        public static string MainToolEditAppSettings {
            get {
                return ResourceManager.GetString("MainToolEditAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit color scheme for waterfall diagram.
        /// </summary>
        public static string MainToolEditColorScheme {
            get {
                return ResourceManager.GetString("MainToolEditColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit species information.
        /// </summary>
        public static string MainToolEditSpeciesInfo {
            get {
                return ResourceManager.GetString("MainToolEditSpeciesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate and classify bat calls in project.
        /// </summary>
        public static string MainToolEvalBatCalls {
            get {
                return ResourceManager.GetString("MainToolEvalBatCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find species by entering call parameters.
        /// </summary>
        public static string MainToolFindSpeciesInfo {
            get {
                return ResourceManager.GetString("MainToolFindSpeciesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate xml information files for current project.
        /// </summary>
        public static string MainToolGenXmlFiles {
            get {
                return ResourceManager.GetString("MainToolGenXmlFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect and manipulate wav files.
        /// </summary>
        public static string MainToolManipWavFiles {
            get {
                return ResourceManager.GetString("MainToolManipWavFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open manual.
        /// </summary>
        public static string MainToolOpenManual {
            get {
                return ResourceManager.GetString("MainToolOpenManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh views.
        /// </summary>
        public static string MainToolRefresh {
            get {
                return ResourceManager.GetString("MainToolRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Report.
        /// </summary>
        public static string MainToolReport {
            get {
                return ResourceManager.GetString("MainToolReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run script.
        /// </summary>
        public static string MainToolRunScript {
            get {
                return ResourceManager.GetString("MainToolRunScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show software info.
        /// </summary>
        public static string MainToolShowSoftwareInfo {
            get {
                return ResourceManager.GetString("MainToolShowSoftwareInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Data.
        /// </summary>
        public static string MainTrainData {
            get {
                return ResourceManager.GetString("MainTrainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project View.
        /// </summary>
        public static string MainWinProjectView {
            get {
                return ResourceManager.GetString("MainWinProjectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fmax.
        /// </summary>
        public static string MaxFrequency {
            get {
                return ResourceManager.GetString("MaxFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fmin.
        /// </summary>
        public static string MinFrequency {
            get {
                return ResourceManager.GetString("MinFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete all selected files?.
        /// </summary>
        public static string msgDeleteFiles {
            get {
                return ResourceManager.GetString("msgDeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset to factory settings?.
        /// </summary>
        public static string msgFactorySettings {
            get {
                return ResourceManager.GetString("msgFactorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string msgInformation {
            get {
                return ResourceManager.GetString("msgInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string msgQuestion {
            get {
                return ResourceManager.GetString("msgQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changed project before closing?.
        /// </summary>
        public static string msgSaveBeforeClose {
            get {
                return ResourceManager.GetString("msgSaveBeforeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable both cursors first!.
        /// </summary>
        public static string msgZoomNotPossible {
            get {
                return ResourceManager.GetString("msgZoomNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point in Time.
        /// </summary>
        public static string PointInTime {
            get {
                return ResourceManager.GetString("PointInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Rate.
        /// </summary>
        public static string SamplingRate {
            get {
                return ResourceManager.GetString("SamplingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select call type.
        /// </summary>
        public static string SelectCallType {
            get {
                return ResourceManager.GetString("SelectCallType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide call related information in overview.
        /// </summary>
        public static string SerDescHideCallInfo {
            get {
                return ResourceManager.GetString("SerDescHideCallInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string SetCatApplication {
            get {
                return ResourceManager.GetString("SetCatApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bat Species.
        /// </summary>
        public static string SetCatBatSpecies {
            get {
                return ResourceManager.GetString("SetCatBatSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Gradient.
        /// </summary>
        public static string SetCatColorGradient {
            get {
                return ResourceManager.GetString("SetCatColorGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string SetCatModel {
            get {
                return ResourceManager.GetString("SetCatModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction.
        /// </summary>
        public static string SetCatPrediction {
            get {
                return ResourceManager.GetString("SetCatPrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting.
        /// </summary>
        public static string SetCatScripting {
            get {
                return ResourceManager.GetString("SetCatScripting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for bat species.
        /// </summary>
        public static string SetDescBatSpecies {
            get {
                return ResourceManager.GetString("SetDescBatSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of Background in XT diagram.
        /// </summary>
        public static string SetDescColorBackgXTDiag {
            get {
                return ResourceManager.GetString("SetDescColorBackgXTDiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of line in XT diagram.
        /// </summary>
        public static string SetDescColorOfLine {
            get {
                return ResourceManager.GetString("SetDescColorOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr of epochs during training of model.
        /// </summary>
        public static string SetDescEpochs {
            get {
                return ResourceManager.GetString("SetDescEpochs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for display filter.
        /// </summary>
        public static string SetDescFilter {
            get {
                return ResourceManager.GetString("SetDescFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height of log control [px].
        /// </summary>
        public static string SetDescHeightLogCtrl {
            get {
                return ResourceManager.GetString("SetDescHeightLogCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height of main window [px].
        /// </summary>
        public static string SetDescHeightMainWin {
            get {
                return ResourceManager.GetString("SetDescHeightMainWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height of waterfall diagram in pixel.
        /// </summary>
        public static string SetDescHeightWf {
            get {
                return ResourceManager.GetString("SetDescHeightWf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set language.
        /// </summary>
        public static string SetDescLanguage {
            get {
                return ResourceManager.GetString("SetDescLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the learning rate to train the model.
        /// </summary>
        public static string SetDescLearningRate {
            get {
                return ResourceManager.GetString("SetDescLearningRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of zoom for automatic zoom to call [ms].
        /// </summary>
        public static string SetDescLengthZoomMs {
            get {
                return ResourceManager.GetString("SetDescLengthZoomMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main window X position.
        /// </summary>
        public static string SetDescMainWinPosX {
            get {
                return ResourceManager.GetString("SetDescMainWinPosX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main window y position.
        /// </summary>
        public static string SetDescMainWinPosY {
            get {
                return ResourceManager.GetString("SetDescMainWinPosY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path to root directory containing the trained AI  models.
        /// </summary>
        public static string SetDescModDir {
            get {
                return ResourceManager.GetString("SetDescModDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal probability to copy automated to manually set probability with copy button.
        /// </summary>
        public static string SetDescProb {
            get {
                return ResourceManager.GetString("SetDescProb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path to python executable for executing python scripts.
        /// </summary>
        public static string SetDescPythonExe {
            get {
                return ResourceManager.GetString("SetDescPythonExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range for color gradient in zoom window [dB].
        /// </summary>
        public static string SetDescRangeZoomWin {
            get {
                return ResourceManager.GetString("SetDescRangeZoomWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling rate needed for AI models.
        /// </summary>
        public static string SetDescSamplingRate {
            get {
                return ResourceManager.GetString("SetDescSamplingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full path to python script to predict bat species.
        /// </summary>
        public static string SetDescScriptPredict {
            get {
                return ResourceManager.GetString("SetDescScriptPredict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full path to R script for determination of call parameters.
        /// </summary>
        public static string SetDescScriptProp {
            get {
                return ResourceManager.GetString("SetDescScriptProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csv file containing list of species supported by automatic species detection.
        /// </summary>
        public static string SetDescSpeciesFile {
            get {
                return ResourceManager.GetString("SetDescSpeciesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define if waterfall diagram should be logarithmic or linear.
        /// </summary>
        public static string SetDescWfLog {
            get {
                return ResourceManager.GetString("SetDescWfLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of FFT in points (MUST be a power of 2).
        /// </summary>
        public static string SetDescWidthFFT {
            get {
                return ResourceManager.GetString("SetDescWidthFFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of file browser [px].
        /// </summary>
        public static string SetDescWidthFileSel {
            get {
                return ResourceManager.GetString("SetDescWidthFileSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of main window [px].
        /// </summary>
        public static string SetDescWidthMainWin {
            get {
                return ResourceManager.GetString("SetDescWidthMainWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string SettingsApplication {
            get {
                return ResourceManager.GetString("SettingsApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/N ratio.
        /// </summary>
        public static string Snr {
            get {
                return ResourceManager.GetString("Snr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 letter abbreviation for species name.
        /// </summary>
        public static string SpecDescAbbr {
            get {
                return ResourceManager.GetString("SpecDescAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapt sample rate to trained model.
        /// </summary>
        public static string SpecDescAdapt {
            get {
                return ResourceManager.GetString("SpecDescAdapt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition of color gradient for color channel blue.
        /// </summary>
        public static string SpecDescColorBlue {
            get {
                return ResourceManager.GetString("SpecDescColorBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition of color gradient for color channel green.
        /// </summary>
        public static string SpecDescColorGreen {
            get {
                return ResourceManager.GetString("SpecDescColorGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition of color gradient for color channel red.
        /// </summary>
        public static string SpecDescColorRed {
            get {
                return ResourceManager.GetString("SpecDescColorRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to execute confidence test.
        /// </summary>
        public static string SpecDescConfTest {
            get {
                return ResourceManager.GetString("SpecDescConfTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut recordings to single calls.
        /// </summary>
        public static string SpecDescCutCalls {
            get {
                return ResourceManager.GetString("SpecDescCutCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete temporary files (wav and data).
        /// </summary>
        public static string SpecDescDelTemp {
            get {
                return ResourceManager.GetString("SpecDescDelTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identify calls and their parameters.
        /// </summary>
        public static string SpecDescIdentify {
            get {
                return ResourceManager.GetString("SpecDescIdentify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin species name.
        /// </summary>
        public static string SpecDescLatinSpec {
            get {
                return ResourceManager.GetString("SpecDescLatinSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal call duration [ms].
        /// </summary>
        public static string SpecDescMaxCall {
            get {
                return ResourceManager.GetString("SpecDescMaxCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal call diatance [ms].
        /// </summary>
        public static string SpecDescMaxCallDist {
            get {
                return ResourceManager.GetString("SpecDescMaxCallDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal call duration [ms].
        /// </summary>
        public static string SpecDescMinCall {
            get {
                return ResourceManager.GetString("SpecDescMinCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal call diatance [ms].
        /// </summary>
        public static string SpecDescMinCallDist {
            get {
                return ResourceManager.GetString("SpecDescMinCallDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute species prediciton.
        /// </summary>
        public static string SpecDescPredict {
            get {
                return ResourceManager.GetString("SpecDescPredict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare data fro prediciton.
        /// </summary>
        public static string SpecDescPrepData {
            get {
                return ResourceManager.GetString("SpecDescPrepData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show species in comboboxes to select species.
        /// </summary>
        public static string SpecDescShowSpec {
            get {
                return ResourceManager.GetString("SpecDescShowSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show zoom view in a separate window side by side to main window.
        /// </summary>
        public static string SpecDescShowZoom {
            get {
                return ResourceManager.GetString("SpecDescShowZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full path to Wav example file.
        /// </summary>
        public static string SpecDescWav {
            get {
                return ResourceManager.GetString("SpecDescWav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of waterfall diagram in pixel.
        /// </summary>
        public static string SpecDescWidthWf {
            get {
                return ResourceManager.GetString("SpecDescWidthWf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decrease dynamic range.
        /// </summary>
        public static string ToolTipDecRange {
            get {
                return ResourceManager.GetString("ToolTipDecRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to increase dynamic range.
        /// </summary>
        public static string ToolTipIncRange {
            get {
                return ResourceManager.GetString("ToolTipIncRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down (decreasing frequency).
        /// </summary>
        public static string ToolTipMoveDownF {
            get {
                return ResourceManager.GetString("ToolTipMoveDownF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move left (decreasing time).
        /// </summary>
        public static string ToolTipMoveLeftT {
            get {
                return ResourceManager.GetString("ToolTipMoveLeftT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move right (increasing time).
        /// </summary>
        public static string ToolTipMoveRightIT {
            get {
                return ResourceManager.GetString("ToolTipMoveRightIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up (increasing frequency).
        /// </summary>
        public static string ToolTipMoveUpF {
            get {
                return ResourceManager.GetString("ToolTipMoveUpF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play displayed section.
        /// </summary>
        public static string ToolTipPlayDispSection {
            get {
                return ResourceManager.GetString("ToolTipPlayDispSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play displayed section, stretched 10x.
        /// </summary>
        public static string ToolTipPlayDispSection10x {
            get {
                return ResourceManager.GetString("ToolTipPlayDispSection10x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play displayed section, stretched 20x.
        /// </summary>
        public static string ToolTipPlayDispSection20x {
            get {
                return ResourceManager.GetString("ToolTipPlayDispSection20x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save settings.
        /// </summary>
        public static string ToolTipSaveSettings {
            get {
                return ResourceManager.GetString("ToolTipSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop playing audio.
        /// </summary>
        public static string ToolTipStopPlayingAudio {
            get {
                return ResourceManager.GetString("ToolTipStopPlayingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in x2 horizontally.
        /// </summary>
        public static string ToolTipZoomInX2H {
            get {
                return ResourceManager.GetString("ToolTipZoomInX2H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in x2 vertically.
        /// </summary>
        public static string TooltipZoomInX2V {
            get {
                return ResourceManager.GetString("TooltipZoomInX2V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out to total image.
        /// </summary>
        public static string ToolTipZoomOutTotal {
            get {
                return ResourceManager.GetString("ToolTipZoomOutTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out x2 horizontally.
        /// </summary>
        public static string ToolTipZoomOutX2Horizontally {
            get {
                return ResourceManager.GetString("ToolTipZoomOutX2Horizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out x2 vertically.
        /// </summary>
        public static string ToolTipZoomOutX2V {
            get {
                return ResourceManager.GetString("ToolTipZoomOutX2V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to cursor.
        /// </summary>
        public static string ToolTipZoomToCursor {
            get {
                return ResourceManager.GetString("ToolTipZoomToCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
