//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace BatInspector
{

  // 
  // Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.3928.0.
  // 


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
  public partial class item
  {

    private itemKey[] keyField;

    private itemValue[] valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("key", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public itemKey[] key
    {
      get
      {
        return this.keyField;
      }
      set
      {
        this.keyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("value", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public itemValue[] value
    {
      get
      {
        return this.valueField;
      }
      set
      {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  public partial class itemKey
  {

    private string stringField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string @string
    {
      get
      {
        return this.stringField;
      }
      set
      {
        this.stringField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  public partial class itemValue
  {

    private string doubleField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string @double
    {
      get
      {
        return this.doubleField;
      }
      set
      {
        this.doubleField = value;
      }
    }
  }

  /// <remarks/>
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
  public class BatRecordBra
  {

    private string nameField;

    private string splitField;

    private string timestampOverrideField;

    private string userMetaDataField;

    private string latOverrideField;

    private string lonOverrideField;

    private string analyseVersionField;

    private string recQualityField;

    private string peakFreqField;

    private string spectLenghtField;

    private string specMaxValField;

    private string noiseIntensityField;

    private string ratingField;

    private string markedField;

    private string foreignField;

    private string channelDisplayedField;

    private string channelAnalysedField;

    private BatRecordLocationData[] locationDataField;

    private BatRecordCall[] callField;

    private BatRecordSpecies1[] species1Field;

    private BatRecordSpecies2[] species2Field;

    private item[] batSpeciesListField;

    private item[] batGenusListField;

    private string timestampField;

    private string chkField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Split
    {
      get
      {
        return this.splitField;
      }
      set
      {
        this.splitField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TimestampOverride
    {
      get
      {
        return this.timestampOverrideField;
      }
      set
      {
        this.timestampOverrideField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UserMetaData
    {
      get
      {
        return this.userMetaDataField;
      }
      set
      {
        this.userMetaDataField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LatOverride
    {
      get
      {
        return this.latOverrideField;
      }
      set
      {
        this.latOverrideField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LonOverride
    {
      get
      {
        return this.lonOverrideField;
      }
      set
      {
        this.lonOverrideField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AnalyseVersion
    {
      get
      {
        return this.analyseVersionField;
      }
      set
      {
        this.analyseVersionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RecQuality
    {
      get
      {
        return this.recQualityField;
      }
      set
      {
        this.recQualityField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PeakFreq
    {
      get
      {
        return this.peakFreqField;
      }
      set
      {
        this.peakFreqField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SpectLenght
    {
      get
      {
        return this.spectLenghtField;
      }
      set
      {
        this.spectLenghtField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SpecMaxVal
    {
      get
      {
        return this.specMaxValField;
      }
      set
      {
        this.specMaxValField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NoiseIntensity
    {
      get
      {
        return this.noiseIntensityField;
      }
      set
      {
        this.noiseIntensityField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Rating
    {
      get
      {
        return this.ratingField;
      }
      set
      {
        this.ratingField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Marked
    {
      get
      {
        return this.markedField;
      }
      set
      {
        this.markedField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Foreign
    {
      get
      {
        return this.foreignField;
      }
      set
      {
        this.foreignField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ChannelDisplayed
    {
      get
      {
        return this.channelDisplayedField;
      }
      set
      {
        this.channelDisplayedField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ChannelAnalysed
    {
      get
      {
        return this.channelAnalysedField;
      }
      set
      {
        this.channelAnalysedField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LocationData", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BatRecordLocationData[] LocationData
    {
      get
      {
        return this.locationDataField;
      }
      set
      {
        this.locationDataField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Call", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BatRecordCall[] Call
    {
      get
      {
        return this.callField;
      }
      set
      {
        this.callField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Species1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BatRecordSpecies1[] Species1
    {
      get
      {
        return this.species1Field;
      }
      set
      {
        this.species1Field = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Species2", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BatRecordSpecies2[] Species2
    {
      get
      {
        return this.species2Field;
      }
      set
      {
        this.species2Field = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", typeof(item), IsNullable = false)]
    public item[] BatSpeciesList
    {
      get
      {
        return this.batSpeciesListField;
      }
      set
      {
        this.batSpeciesListField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", typeof(item), IsNullable = false)]
    public item[] BatGenusList
    {
      get
      {
        return this.batGenusListField;
      }
      set
      {
        this.batGenusListField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Timestamp
    {
      get
      {
        return this.timestampField;
      }
      set
      {
        this.timestampField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string chk
    {
      get
      {
        return this.chkField;
      }
      set
      {
        this.chkField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  public partial class BatRecordLocationData
  {

    private string addressField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Address
    {
      get
      {
        return this.addressField;
      }
      set
      {
        this.addressField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  public partial class BatRecordCall
  {

    private double beginField;

    private double endField;

    private double maxFreqField;

    private double minFreqField;

    private string peakFreqField;

    private string peakFreqIndexField;

    private string peakFreqsField;

    private string intensityField;

    private string noiseField;

    private string periodicityField;

    private string wavinessField;

    private string shapeField;

    private string callTypeField;

    private string speciesField;

    private string customField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Begin
    {
      get
      {
        return this.beginField;
      }
      set
      {
        this.beginField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double End
    {
      get
      {
        return this.endField;
      }
      set
      {
        this.endField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double MaxFreq
    {
      get
      {
        return this.maxFreqField;
      }
      set
      {
        this.maxFreqField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double MinFreq
    {
      get
      {
        return this.minFreqField;
      }
      set
      {
        this.minFreqField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PeakFreq
    {
      get
      {
        return this.peakFreqField;
      }
      set
      {
        this.peakFreqField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PeakFreqIndex
    {
      get
      {
        return this.peakFreqIndexField;
      }
      set
      {
        this.peakFreqIndexField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PeakFreqs
    {
      get
      {
        return this.peakFreqsField;
      }
      set
      {
        this.peakFreqsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Intensity
    {
      get
      {
        return this.intensityField;
      }
      set
      {
        this.intensityField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Noise
    {
      get
      {
        return this.noiseField;
      }
      set
      {
        this.noiseField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Periodicity
    {
      get
      {
        return this.periodicityField;
      }
      set
      {
        this.periodicityField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Waviness
    {
      get
      {
        return this.wavinessField;
      }
      set
      {
        this.wavinessField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Shape
    {
      get
      {
        return this.shapeField;
      }
      set
      {
        this.shapeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CallType
    {
      get
      {
        return this.callTypeField;
      }
      set
      {
        this.callTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Species
    {
      get
      {
        return this.speciesField;
      }
      set
      {
        this.speciesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Custom
    {
      get
      {
        return this.customField;
      }
      set
      {
        this.customField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  public partial class BatRecordSpecies1
  {

    private string genusField;

    private string speciesField;

    private string plausibilityField;

    private string sourceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Genus
    {
      get
      {
        return this.genusField;
      }
      set
      {
        this.genusField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Species
    {
      get
      {
        return this.speciesField;
      }
      set
      {
        this.speciesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Plausibility
    {
      get
      {
        return this.plausibilityField;
      }
      set
      {
        this.plausibilityField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Source
    {
      get
      {
        return this.sourceField;
      }
      set
      {
        this.sourceField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  public partial class BatRecordSpecies2
  {

    private string plausibilityField;

    private string sourceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Plausibility
    {
      get
      {
        return this.plausibilityField;
      }
      set
      {
        this.plausibilityField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Source
    {
      get
      {
        return this.sourceField;
      }
      set
      {
        this.sourceField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
  public partial class NewDataSet
  {

    private object[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BatRecord", typeof(BatRecordBra))]
    [System.Xml.Serialization.XmlElementAttribute("item", typeof(item))]
    public object[] Items
    {
      get
      {
        return this.itemsField;
      }
      set
      {
        this.itemsField = value;
      }
    }
  }
}
