//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
public partial class kml {
    
    private kmlDocument itemsField;
    
    [System.Xml.Serialization.XmlElementAttribute("Document")]
    public kmlDocument Doc{ get {return this.itemsField;}  set {this.itemsField = value;}}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
public partial class kmlDocument {
    
    
    private kmlDocumentPlacemark[] placemarkField;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Placemark")]
    public kmlDocumentPlacemark[] Placemark { get { return this.placemarkField; } set {this.placemarkField = value;}}
}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
public partial class kmlDocumentPlacemark {
    
    private string descriptionField;
    
    private string nameField;
    
    private string styleUrlField;
    
    private kmlDocumentPlacemarkExtendedDataData[] extendedDataField;
    
    private kmlDocumentPlacemarkLineString lineStringField;
    
    private kmlDocumentPlacemarkPoint pointField;
    
    public string description { get {return this.descriptionField; } set {this.descriptionField = value;} }
    
    public string name { get { return this.nameField; }  set { this.nameField = value; } }
    
    public string styleUrl { get { return this.styleUrlField; }  set {this.styleUrlField = value; } }
    
    [System.Xml.Serialization.XmlElementAttribute("Data", typeof(kmlDocumentPlacemarkExtendedDataData), IsNullable=false)]
    public kmlDocumentPlacemarkExtendedDataData[] ExtendedData { get { return this.extendedDataField; }  set {this.extendedDataField = value; }  }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LineString")]
    public kmlDocumentPlacemarkLineString LineString { get { return this.lineStringField; }  set {this.lineStringField = value; }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Point")]
    public kmlDocumentPlacemarkPoint Point { get {return this.pointField; } set { this.pointField = value; } }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
public partial class kmlDocumentPlacemarkExtendedDataData {
    
    private string valueField;
    
    private string nameField;
    
    /// <remarks/>
    public string value { get { return this.valueField; } set {this.valueField = value; } }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name { get {return this.nameField; }  set {this.nameField = value; } }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
public partial class kmlDocumentPlacemarkLineString {
    
    private string coordinatesField;
        
    /// <remarks/>
    public string coordinates { get { return this.coordinatesField; }  set { this.coordinatesField = value; }  }
    
    /// <remarks/>
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
public partial class kmlDocumentPlacemarkPoint {
    
    private string coordinatesField;
    
    /// <remarks/>
    public string coordinates { get { return this.coordinatesField; } set {this.coordinatesField = value; }  }
}
