name: batdetect2
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - matplotlib
  - pandas
  - scikit-learn
  - numpy
  - pytorch
  - scipy
  - torchvision
  - librosa
  - torchaudio
